meta_learner: maml
fomaml: True
proto_maml: False
meta_model: seq
learner_model: mlp
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 1024
  dropout_ratio: 0
vectors: elmo
output_lr: 0.1
learner_lr: 0.01
meta_lr: 0.005
meta_batch_size: 16
num_shots:
  wsd: 8
num_updates: 7
num_test_samples:
  wsd: 8
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 167
num_test_episodes:
  wsd: 264
num_meta_epochs: 25
early_stopping: 2
device: cuda:0