meta_learner: nearest_neighbor
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 768
vectors: bert
num_shots:
  wsd: 16
num_test_samples:
  wsd: 16
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 146
num_test_episodes:
  wsd: 197
device: cuda:0
