meta_learner: majority
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 1024
num_shots:
  wsd: 4
num_updates: 5
num_test_samples:
  wsd: 4
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 166
num_test_episodes:
  wsd: 270
device: cuda:0
