meta_learner: majority
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 1024
num_shots:
  wsd: 16
num_test_samples:
  wsd: 16
num_train_episodes:
  wsd: 100000
num_val_episodes:
  wsd: 208
num_test_episodes:
  wsd: 183
device: cuda:0
