meta_learner: majority
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: 5612
  embed_dim: 1024
num_shots:
  wsd: 16
num_test_samples:
  wsd: 16
num_train_episodes:
  wsd: 400
num_test_episodes:
  wsd: 200
device: cpu #cuda:0
