meta_learner: maml
meta_model: seq_meta_model
learner_params:
  hidden_size: 128
  num_outputs:
    pos: 18
    wsd: 45596
    metaphor: 2
  embed_dim: 1024
learner_lr: 0.01
num_shots:
  pos: 64
  wsd: 64
  metaphor: 64
num_updates: 1
num_test_samples:
  pos: 64
  wsd: 64
  metaphor: 64
num_episodes:
  pos: 1
  wsd: 1
  metaphor: 1
num_meta_epochs: 5
early_stopping: 10
proto_maml: false
