meta_learner: nearest_neighbor
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 1024
num_shots:
  wsd: 32
num_updates: 5
num_test_samples:
  wsd: 32
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 84
num_test_episodes:
  wsd: 129
device: cuda:0
