meta_learner: proto_net
meta_model: seq_meta_model
learner_model: seq
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: 5612
  embed_dim: 300
  dropout_ratio: 0
vectors: glove
meta_lr: 0.1
num_shots:
  wsd: 16
num_updates: 5
num_test_samples:
  wsd: 16
num_train_episodes:
  wsd: 10000
num_val_episodes:
  wsd: 208
num_test_episodes:
  wsd: 183
num_meta_epochs: 1000
early_stopping: 10
device: cuda:0
