meta_learner: maml
fomaml: True
proto_maml: True
meta_model: seq
learner_model: seq
learner_params:
  hidden_size: 256
  num_outputs:
    wsd: var
  embed_dim: 300
  dropout_ratio: 0
vectors: glove
learner_lr: 0.1
meta_lr: 0.001
meta_batch_size: 100
num_shots:
  wsd: 16
num_updates: 5
num_test_samples:
  wsd: 16
num_train_episodes:
  wsd: 100000
num_val_episodes:
  wsd: 208
num_test_episodes:
  wsd: 183
num_meta_epochs: 1000
early_stopping: 5
device: cuda:0
